// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "admin.proto" (package "yarsha.admin.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AdminService } from "./admin";
import type { RemoveParticipantsResponseWrapper } from "./admin";
import type { RemoveParticipantsRequestWrapper } from "./admin";
import type { RemoveAdminsResponseWrapper } from "./admin";
import type { RemoveAdminsRequestWrapper } from "./admin";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { AddAdminsResponseWrapper } from "./admin";
import type { AddAdminsRequestWrapper } from "./admin";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service yarsha.admin.v1.AdminService
 */
export interface IAdminServiceClient {
    /**
     * @generated from protobuf rpc: AddAdmins(yarsha.admin.v1.AddAdminsRequestWrapper) returns (yarsha.admin.v1.AddAdminsResponseWrapper);
     */
    addAdmins(input: AddAdminsRequestWrapper, options?: RpcOptions): UnaryCall<AddAdminsRequestWrapper, AddAdminsResponseWrapper>;
    /**
     * @generated from protobuf rpc: RemoveAdmins(yarsha.admin.v1.RemoveAdminsRequestWrapper) returns (yarsha.admin.v1.RemoveAdminsResponseWrapper);
     */
    removeAdmins(input: RemoveAdminsRequestWrapper, options?: RpcOptions): UnaryCall<RemoveAdminsRequestWrapper, RemoveAdminsResponseWrapper>;
    /**
     * @generated from protobuf rpc: RemoveParticipants(yarsha.admin.v1.RemoveParticipantsRequestWrapper) returns (yarsha.admin.v1.RemoveParticipantsResponseWrapper);
     */
    removeParticipants(input: RemoveParticipantsRequestWrapper, options?: RpcOptions): UnaryCall<RemoveParticipantsRequestWrapper, RemoveParticipantsResponseWrapper>;
}
/**
 * @generated from protobuf service yarsha.admin.v1.AdminService
 */
export class AdminServiceClient implements IAdminServiceClient, ServiceInfo {
    typeName = AdminService.typeName;
    methods = AdminService.methods;
    options = AdminService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: AddAdmins(yarsha.admin.v1.AddAdminsRequestWrapper) returns (yarsha.admin.v1.AddAdminsResponseWrapper);
     */
    addAdmins(input: AddAdminsRequestWrapper, options?: RpcOptions): UnaryCall<AddAdminsRequestWrapper, AddAdminsResponseWrapper> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddAdminsRequestWrapper, AddAdminsResponseWrapper>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemoveAdmins(yarsha.admin.v1.RemoveAdminsRequestWrapper) returns (yarsha.admin.v1.RemoveAdminsResponseWrapper);
     */
    removeAdmins(input: RemoveAdminsRequestWrapper, options?: RpcOptions): UnaryCall<RemoveAdminsRequestWrapper, RemoveAdminsResponseWrapper> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoveAdminsRequestWrapper, RemoveAdminsResponseWrapper>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemoveParticipants(yarsha.admin.v1.RemoveParticipantsRequestWrapper) returns (yarsha.admin.v1.RemoveParticipantsResponseWrapper);
     */
    removeParticipants(input: RemoveParticipantsRequestWrapper, options?: RpcOptions): UnaryCall<RemoveParticipantsRequestWrapper, RemoveParticipantsResponseWrapper> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoveParticipantsRequestWrapper, RemoveParticipantsResponseWrapper>("unary", this._transport, method, opt, input);
    }
}
