// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "message.proto" (package "yarsha.message.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { MessageService } from "./message";
import type { UnpinMessageResponse } from "./message";
import type { UnpinMessageRequest } from "./message";
import type { PinMessageResponse } from "./message";
import type { PinMessageRequest } from "./message";
import type { ReactToMessageResponse } from "./message";
import type { ReactToMessageRequest } from "./message";
import type { GetChatMessagesResponse } from "./message";
import type { GetChatMessagesRequest } from "./message";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SendMessageResponse } from "./message";
import type { SendMessageRequest } from "./message";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service yarsha.message.v1.MessageService
 */
export interface IMessageServiceClient {
    /**
     * @generated from protobuf rpc: SendMessage(yarsha.message.v1.SendMessageRequest) returns (yarsha.message.v1.SendMessageResponse);
     */
    sendMessage(input: SendMessageRequest, options?: RpcOptions): UnaryCall<SendMessageRequest, SendMessageResponse>;
    /**
     * @generated from protobuf rpc: GetChatMessages(yarsha.message.v1.GetChatMessagesRequest) returns (yarsha.message.v1.GetChatMessagesResponse);
     */
    getChatMessages(input: GetChatMessagesRequest, options?: RpcOptions): UnaryCall<GetChatMessagesRequest, GetChatMessagesResponse>;
    /**
     * @generated from protobuf rpc: ReactToMessage(yarsha.message.v1.ReactToMessageRequest) returns (yarsha.message.v1.ReactToMessageResponse);
     */
    reactToMessage(input: ReactToMessageRequest, options?: RpcOptions): UnaryCall<ReactToMessageRequest, ReactToMessageResponse>;
    /**
     * @generated from protobuf rpc: PinMessage(yarsha.message.v1.PinMessageRequest) returns (yarsha.message.v1.PinMessageResponse);
     */
    pinMessage(input: PinMessageRequest, options?: RpcOptions): UnaryCall<PinMessageRequest, PinMessageResponse>;
    /**
     * @generated from protobuf rpc: UnpinMessage(yarsha.message.v1.UnpinMessageRequest) returns (yarsha.message.v1.UnpinMessageResponse);
     */
    unpinMessage(input: UnpinMessageRequest, options?: RpcOptions): UnaryCall<UnpinMessageRequest, UnpinMessageResponse>;
}
/**
 * @generated from protobuf service yarsha.message.v1.MessageService
 */
export class MessageServiceClient implements IMessageServiceClient, ServiceInfo {
    typeName = MessageService.typeName;
    methods = MessageService.methods;
    options = MessageService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: SendMessage(yarsha.message.v1.SendMessageRequest) returns (yarsha.message.v1.SendMessageResponse);
     */
    sendMessage(input: SendMessageRequest, options?: RpcOptions): UnaryCall<SendMessageRequest, SendMessageResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SendMessageRequest, SendMessageResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetChatMessages(yarsha.message.v1.GetChatMessagesRequest) returns (yarsha.message.v1.GetChatMessagesResponse);
     */
    getChatMessages(input: GetChatMessagesRequest, options?: RpcOptions): UnaryCall<GetChatMessagesRequest, GetChatMessagesResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetChatMessagesRequest, GetChatMessagesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReactToMessage(yarsha.message.v1.ReactToMessageRequest) returns (yarsha.message.v1.ReactToMessageResponse);
     */
    reactToMessage(input: ReactToMessageRequest, options?: RpcOptions): UnaryCall<ReactToMessageRequest, ReactToMessageResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReactToMessageRequest, ReactToMessageResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: PinMessage(yarsha.message.v1.PinMessageRequest) returns (yarsha.message.v1.PinMessageResponse);
     */
    pinMessage(input: PinMessageRequest, options?: RpcOptions): UnaryCall<PinMessageRequest, PinMessageResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<PinMessageRequest, PinMessageResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UnpinMessage(yarsha.message.v1.UnpinMessageRequest) returns (yarsha.message.v1.UnpinMessageResponse);
     */
    unpinMessage(input: UnpinMessageRequest, options?: RpcOptions): UnaryCall<UnpinMessageRequest, UnpinMessageResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<UnpinMessageRequest, UnpinMessageResponse>("unary", this._transport, method, opt, input);
    }
}
