// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "users.proto" (package "yarsha.users.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { UserService } from "./users";
import type { DeleteAccountResponse } from "./users";
import type { DeleteAccountRequest } from "./users";
import type { LogoutResponse } from "./users";
import type { LogoutRequest } from "./users";
import type { CheckYarshaUserResponse } from "./users";
import type { CheckYarshaUserRequest } from "./users";
import type { UpdateUserResponse } from "./users";
import type { UpdateUserRequest } from "./users";
import type { SearchUsersResponse } from "./users";
import type { SearchUsersRequest } from "./users";
import type { GetUserInfoResponse } from "./users";
import type { GetUserInfoRequest } from "./users";
import type { VerifyOtpResponse } from "./users";
import type { VerifyOtpRequest } from "./users";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SendOtpResponse } from "./users";
import type { SendOtpRequest } from "./users";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service yarsha.users.v1.UserService
 */
export interface IUserServiceClient {
    /**
     * @generated from protobuf rpc: SendOtp(yarsha.users.v1.SendOtpRequest) returns (yarsha.users.v1.SendOtpResponse);
     */
    sendOtp(input: SendOtpRequest, options?: RpcOptions): UnaryCall<SendOtpRequest, SendOtpResponse>;
    /**
     * @generated from protobuf rpc: VerifyOtp(yarsha.users.v1.VerifyOtpRequest) returns (yarsha.users.v1.VerifyOtpResponse);
     */
    verifyOtp(input: VerifyOtpRequest, options?: RpcOptions): UnaryCall<VerifyOtpRequest, VerifyOtpResponse>;
    /**
     * @generated from protobuf rpc: GetUserById(yarsha.users.v1.GetUserInfoRequest) returns (yarsha.users.v1.GetUserInfoResponse);
     */
    getUserById(input: GetUserInfoRequest, options?: RpcOptions): UnaryCall<GetUserInfoRequest, GetUserInfoResponse>;
    /**
     * @generated from protobuf rpc: SearchUsers(yarsha.users.v1.SearchUsersRequest) returns (yarsha.users.v1.SearchUsersResponse);
     */
    searchUsers(input: SearchUsersRequest, options?: RpcOptions): UnaryCall<SearchUsersRequest, SearchUsersResponse>;
    /**
     * @generated from protobuf rpc: UpdateUserProfile(yarsha.users.v1.UpdateUserRequest) returns (yarsha.users.v1.UpdateUserResponse);
     */
    updateUserProfile(input: UpdateUserRequest, options?: RpcOptions): UnaryCall<UpdateUserRequest, UpdateUserResponse>;
    /**
     * @generated from protobuf rpc: CheckYarshaUser(yarsha.users.v1.CheckYarshaUserRequest) returns (yarsha.users.v1.CheckYarshaUserResponse);
     */
    checkYarshaUser(input: CheckYarshaUserRequest, options?: RpcOptions): UnaryCall<CheckYarshaUserRequest, CheckYarshaUserResponse>;
    /**
     * @generated from protobuf rpc: Logout(yarsha.users.v1.LogoutRequest) returns (yarsha.users.v1.LogoutResponse);
     */
    logout(input: LogoutRequest, options?: RpcOptions): UnaryCall<LogoutRequest, LogoutResponse>;
    /**
     * @generated from protobuf rpc: DeleteAccount(yarsha.users.v1.DeleteAccountRequest) returns (yarsha.users.v1.DeleteAccountResponse);
     */
    deleteAccount(input: DeleteAccountRequest, options?: RpcOptions): UnaryCall<DeleteAccountRequest, DeleteAccountResponse>;
}
/**
 * @generated from protobuf service yarsha.users.v1.UserService
 */
export class UserServiceClient implements IUserServiceClient, ServiceInfo {
    typeName = UserService.typeName;
    methods = UserService.methods;
    options = UserService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: SendOtp(yarsha.users.v1.SendOtpRequest) returns (yarsha.users.v1.SendOtpResponse);
     */
    sendOtp(input: SendOtpRequest, options?: RpcOptions): UnaryCall<SendOtpRequest, SendOtpResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SendOtpRequest, SendOtpResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: VerifyOtp(yarsha.users.v1.VerifyOtpRequest) returns (yarsha.users.v1.VerifyOtpResponse);
     */
    verifyOtp(input: VerifyOtpRequest, options?: RpcOptions): UnaryCall<VerifyOtpRequest, VerifyOtpResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<VerifyOtpRequest, VerifyOtpResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetUserById(yarsha.users.v1.GetUserInfoRequest) returns (yarsha.users.v1.GetUserInfoResponse);
     */
    getUserById(input: GetUserInfoRequest, options?: RpcOptions): UnaryCall<GetUserInfoRequest, GetUserInfoResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetUserInfoRequest, GetUserInfoResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SearchUsers(yarsha.users.v1.SearchUsersRequest) returns (yarsha.users.v1.SearchUsersResponse);
     */
    searchUsers(input: SearchUsersRequest, options?: RpcOptions): UnaryCall<SearchUsersRequest, SearchUsersResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchUsersRequest, SearchUsersResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateUserProfile(yarsha.users.v1.UpdateUserRequest) returns (yarsha.users.v1.UpdateUserResponse);
     */
    updateUserProfile(input: UpdateUserRequest, options?: RpcOptions): UnaryCall<UpdateUserRequest, UpdateUserResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateUserRequest, UpdateUserResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CheckYarshaUser(yarsha.users.v1.CheckYarshaUserRequest) returns (yarsha.users.v1.CheckYarshaUserResponse);
     */
    checkYarshaUser(input: CheckYarshaUserRequest, options?: RpcOptions): UnaryCall<CheckYarshaUserRequest, CheckYarshaUserResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<CheckYarshaUserRequest, CheckYarshaUserResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Logout(yarsha.users.v1.LogoutRequest) returns (yarsha.users.v1.LogoutResponse);
     */
    logout(input: LogoutRequest, options?: RpcOptions): UnaryCall<LogoutRequest, LogoutResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<LogoutRequest, LogoutResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteAccount(yarsha.users.v1.DeleteAccountRequest) returns (yarsha.users.v1.DeleteAccountResponse);
     */
    deleteAccount(input: DeleteAccountRequest, options?: RpcOptions): UnaryCall<DeleteAccountRequest, DeleteAccountResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteAccountRequest, DeleteAccountResponse>("unary", this._transport, method, opt, input);
    }
}
