import {APP_BASE_URL, GROUP_CHAT_SUBSCRIBE, SOCKET_URL} from './config';

export const URL_CONFIGURATIONS = {
  BASE_URL: APP_BASE_URL,

  APP_URL: APP_BASE_URL,

  API_PREFIX: APP_BASE_URL + '/api',
};

export const SOCKET_COLLECTIONS = {
  MESSAGE_SEND_SOCKET: SOCKET_URL,
  GROUP_CHAT_SUBSCRIBE: GROUP_CHAT_SUBSCRIBE,
};
export const ENDPOINT_COLLECTIONS = {
  OTP_URL: URL_CONFIGURATIONS.API_PREFIX + '/users/send-otp',
  VERIFY_OTP_URL: URL_CONFIGURATIONS.API_PREFIX + '/users/verify-otp',
  GET_USER_URL: URL_CONFIGURATIONS.API_PREFIX + '/users/get-user',
  UPDATE_PROFILE_URL: URL_CONFIGURATIONS.API_PREFIX + '/users/update-profile',
  UPLOAD_PROFILE_PICTURE_URL:
    URL_CONFIGURATIONS.API_PREFIX + '/users/profile-picture',
  FETCH_CHATS_URL: URL_CONFIGURATIONS.API_PREFIX + '/group-chats/list',
  FETCH_CHAT_MESSAGES_URL: URL_CONFIGURATIONS.API_PREFIX + '/messages/get-chat-messages',
  FETCH_CHAT_DETAIL_URL: URL_CONFIGURATIONS.API_PREFIX + '/group-chats/details',
  CREATE_CHAT_URL: URL_CONFIGURATIONS.API_PREFIX + '/group-chats/create',
  CHECK_INDIVIDUAL_CHAT_URL: URL_CONFIGURATIONS.API_PREFIX + '/group-chats/check-individual-chat',
  SEARCH_USER_URL: URL_CONFIGURATIONS.API_PREFIX + '/users/search',
  ADD_MEMBERS: URL_CONFIGURATIONS.API_PREFIX+'/group-chats/add-participants',
  CHECK_YARSHA_USERS_URL: URL_CONFIGURATIONS.API_PREFIX + '/users/check-yarsha-users',
};
