export const APP_SECRETS = {
  IS_PROFILE_SETUP: 'IS_PROFILE_SETUP',
  MNEMONIC: 'MNEMONIC',
  PASSWORD: 'USER_PASSWORD',
  REGISTERED_FCM_TOKEN: 'FCM_TOKEN',
  REGISTERED_APNS_TOKEN: 'APNS_TOKEN',
  ENCRYPTED_MNEMONIC: 'ENCRYPTED_MNEMONIC',
  BIO_METRICS_ENABLED: 'BIOMETRICS_ENABLED',
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  BIO_LOCKED: 'BIO_LOCKED',
  BIO_VERIFIED: 'BIO_VERIFIED',
};

export const APP_STATIC_RESPONSE_MESSAGE = {
  BIOMETRICS_AUTHENTICATION_SUCCESS: 'Authentication successful',
  BIOMETRICS_AUTHENTICATION_FAILED: 'Authentication failed',
};

export const API_RESPONSE_MESSAGE = {
  GROUP_CHAT_CREATED_SUCCESSFULLY: 'Group chat created successfully',
};

export const APP_SECRETS_BIOMETRICS_RESPONSE = {
  CAN_OPEN_SCANNER: 'true',
};

export const APP_ACTIVE_SCREEN = {
  ACTIVE_SCREEN: 'ACTIVE_SCREEN_NAME',
};

export const RESULTS = {
  GRANTED: 'Granted',
  LIMITED: 'Limited',
  DENIED: 'Denied',
  BLOCKED: 'Blocked',
};
